name: CI

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install
        
      - name: Lint
        run: bun run check

      - name: Type-check
        run: bun run check:ts

      - name: Test
        run: bun run test

      # TODO: Test coverage
